blank_issues_enabled: true
contact_links:
  - name: "Discord: GameDev.net"
    url: https://discord.gg/nxAZMPU
    about: You can ping @MaulingMonkey about stuff here
  - name: "Discord: The Rust Programming Language"
    url: https://discord.gg/rust-lang
    about: You can ping @MaulingMonkey about stuff here
  - name: "Discord: Rust Programming Language Community Server"
    url: https://bit.ly/rust-community
    about: You can ping @MaulingMonkey about stuff here
